FROM node:22-alpine

WORKDIR /agent

RUN apk add --no-cache \
    python3 \
    bash \
    make \
    g++ \
    libc6-compat \
    ripgrep

COPY package*.json ./

RUN npm install



COPY . .

RUN mkdir -p /workspace

EXPOSE 3000

CMD ["node", "server.js"]