FROM node:22-bookworm-slim

WORKDIR /agent

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    bash \
    && rm -rf /var/lib/apt/lists/* \
    ripgrep

COPY package*.json ./

RUN npm install

COPY . .

RUN mkdir -p /workspace

EXPOSE 3000

CMD ["node", "server.js"]