apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
  labels:
    app: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router-container
        image: router-image:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: "400Mi"
            cpu: "400m"
          requests:
            memory: "200Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5