export const LANGUAGE_BY_EXTENSION = {
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  json: 'json',
  css: 'css',
  scss: 'scss',
  less: 'less',
  html: 'html',
  htm: 'html',
  md: 'markdown',
  markdown: 'markdown',
  py: 'python',
  java: 'java',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  h: 'c',
  c: 'c',
  hpp: 'cpp',
  yml: 'yaml',
  yaml: 'yaml',
  env: 'plaintext',
  sh: 'shell',
  bash: 'shell',
  dockerfile: 'dockerfile',
  xml: 'xml',
  svg: 'xml',
  sql: 'sql',
  go: 'go',
  rs: 'rust',
  php: 'php',
  rb: 'ruby',
  kt: 'kotlin',
  swift: 'swift',
  txt: 'plaintext',
}

export const BINARY_EXTENSIONS = new Set([
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'ico',
  'woff',
  'woff2',
  'ttf',
  'eot',
  'mp4',
  'webm',
  'zip',
  'gz',
])
